version: "3.8"
services:
  #web:
  #  image: nginx
  #  volumes:
  #    - ./docker/web/nginx.conf:/etc/nginx/nginx.conf:ro
  #  depends_on:
  #    - "server"
  #    - "broker"
  #  ports:
  #    - "8082:80"
  web:
    build: .
    image: mrbrax/twitchautomator
    ports:
      - "8082:8080"
    volumes:
      - ./data:/usr/local/share/twitchautomator/data
      # - ./docker/vods:/var/www/twitchautomator/public/vods
      # - ./docker/saved_clips:/var/www/twitchautomator/public/saved_clips
      # - ./docker/saved_vods:/var/www/twitchautomator/public/saved_vods
    environment:
      - NODE_ENV=production
  # cron:
  #   build: ./docker/cron-container/
  #   image: mrbrax/twitchautomator:latest-cron
  # broker:
  #   build: ./client-broker/
  #   image: mrbrax/twitchautomator:latest-broker