# nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-licenses.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-licenses/v0.8.1/bundles/@yarnpkg/plugin-licenses.js"

supportedArchitectures:
  os:
    - current
    - linux
    - win32

yarnPath: .yarn/releases/yarn-3.2.4.cjs

# packageExtensions:
#   "i18next-http-middleware@3.*":
#     dependencies:
#       "express-serve-static-core": "*"