compressionLevel: mixed

enableGlobalCache: false

supportedArchitectures:
    os:
        - current
        - linux
        - win32
        - linux-arm64
    cpu:
        - "x64"
        - "x86"
        - "arm"

yarnPath: .yarn/releases/yarn-4.0.1.cjs
