compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@vue/test-utils@2.*":
    dependencies:
      "@vue/compiler-dom": "*"
  eslint@^8.0.0:
    dependencies:
      "@eslint/eslintrc": ^1.3.3

supportedArchitectures:
  os:
    - current
    - linux
    - win32
    - linux-arm64
  cpu:
    - 'x64'
    - 'x86'
    - 'arm'
    - 'arm64'

yarnPath: .yarn/releases/yarn-4.0.1.cjs
