name: Check Server

on:
  push:
    branches: [ master ]
    paths:
      - "server/**"
  pull_request:
    branches: [ master ]
    paths:
      - "server/**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn    
      - name: yarn install, lint and build
        run: | 
          cd ./server
          yarn 
          yarn lint:ts
          yarn build
