name: Publish develop release

on:
  push:
    branches:
      - develop-ts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run pack (also releases to GitHub)
        run: ./pack-dev.sh
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}